export {default as Navbar} from './Navbar'
export {default as Homepage} from './Homepage'
export {default as AllProducts} from './AllProducts'
export {default as SingleProduct} from './SingleProduct'
export {default as Phones} from './Phones'
export {default as Search} from './Search'